export const SEARCH_FOCUS = 'header/search_focus'
export const SEARCH_BLUR = 'header/search_blur'
export const CHANGE_LIST = 'header/change_list'
export const MOUSE_STATUS_CHANGE = 'header/mouse_status_change'
export const CHANGE_PAGE = 'header/change_page'